[package]
name = "zeal-sdk"
version = "1.0.3"
edition = "2021"
description = "Rust SDK for Zeal Integration Protocol (ZIP)"
authors = ["offbit.ai"]
license = "Apache-2.0"
repository = "https://github.com/offbit-ai/zeal.git"
homepage = "https://github.com/offbit-ai/zeal"
documentation = "https://docs.rs/zeal-sdk"
keywords = ["workflow", "orchestration", "zip", "sdk", "async"]
categories = ["api-bindings", "asynchronous", "web-programming"]
readme = "README.md"

[dependencies]
# Async runtime and utilities
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"
futures-util = "0.3"

# HTTP client
reqwest = { version = "0.11", features = ["json", "stream", "rustls-tls"], default-features = false }

# WebSocket client
tokio-tungstenite = { version = "0.20", features = ["rustls-tls-webpki-roots"] }

# JSON serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = { version = "0.13", optional = true }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# UUID generation
uuid = { version = "1.6", features = ["v4", "serde"] }

# URL parsing
url = "2.4"

# Cryptography and authentication
base64 = "0.21"
hmac = "0.12"
sha2 = "0.10"
rand = "0.8"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"], optional = true }
tracing-opentelemetry = { version = "0.21", optional = true }
opentelemetry = { version = "0.20", optional = true }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Concurrent data structures
tokio-util = "0.7"
arc-swap = "1.6"
parking_lot = "0.12"
pin-project = "1.1"

# HTTP server for webhooks
axum = { version = "0.7", optional = true }
tower = { version = "0.4", optional = true }

# Retry logic
backoff = "0.4"

# Metrics (optional)
metrics = { version = "0.21", optional = true }

[dev-dependencies]
tokio-test = "0.4"
wiremock = "0.5"
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.8"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[features]
default = ["rustls-tls"]

# TLS backends
rustls-tls = ["reqwest/rustls-tls", "tokio-tungstenite/rustls-tls-webpki-roots"]
native-tls = ["reqwest/native-tls", "tokio-tungstenite/native-tls"]

# Performance features
simd = ["simd-json"]
metrics = ["dep:metrics"]

# Telemetry features
telemetry = [
    "tracing-subscriber",
    "tracing-opentelemetry", 
    "opentelemetry"
]

# Webhook server
webhook-server = ["axum", "tower"]

# All features for documentation
full = [
    "simd",
    "metrics", 
    "telemetry",
    "webhook-server"
]

# Examples and benchmarks will be added as needed
# [[bench]]
# name = "json_parsing"
# harness = false